apiVersion: 1

policies:
  - orgId: 1
    receiver: Email IoT Agricola   # receptor por defecto para todas las alertas
    group_by:
      - grafana_folder
      - alertname
      - parcela
    group_wait: 30s        # espera antes de enviar el primer correo del grupo
    group_interval: 5m     # mínimo entre correos del mismo grupo
    repeat_interval: 2h    # re-envío si la alerta sigue activa
    routes:
      # Alertas críticas: re-envío más frecuente
      - receiver: Email IoT Agricola
        matchers:
          - severity = critical
        group_wait: 10s
        group_interval: 2m
        repeat_interval: 30m

      # Alertas de warning: re-envío estándar
      - receiver: Email IoT Agricola
        matchers:
          - severity = warning
        group_wait: 30s
        group_interval: 5m
        repeat_interval: 2h
